pointer-confinement
MirServer/mir pull request #1867
Opened 2020-12-17 11:43 UTC by AlanGriffiths

Add (incomplete) pointer confinement. Notably, there is currently no support for confinement regions.

As this is incomplete, pointer confinement is disabled by default, to enable:

    `--add-wayland-extensions zwp_pointer_constraints_v1:zwp_relative_pointer_manager_v1`

2020-12-17 11:48 UTC, AlanGriffiths commented
This branch has been "parked" for a while, and it looks like it won't be touched for a further while. After discussion the team agreed it is better to land it behind a feature flag than let it suffer "code rot".

The current implementation is sufficient for various SDL2 based games: in particular, mir-kiosk-neverputt works far better (without the invisible cursor "hitting the screen edged").

2020-12-18 01:06 UTC, wmww requested changes
As expected, it's not ideal for merging but cleaning it up later might be easier than letting it rot out of tree. I'm good with landing once the formatting and floating point input issues are fixed.

2020-12-18 01:06 UTC, wmww commented on src/server/frontend_wayland/wayland_input_dispatcher.cpp
> -    if (send_motion || send_axis)
No need to drop this (probably it was added since you forked off). Obviously it will need to be updated to include `send_position`.

2020-12-18 16:13 UTC, wmww approved these changes
Good enough
bors r+

2020-12-18 16:33 UTC, merged