Do not throw exceptions in surface_destoryed()
MirServer/mir pull request #2056
Opened 2021-06-03 20:29 UTC by wmww

Fixes #2055. Adds a new function to mirwayland (not an ABI break), so check to make sure I did the symbols right.

2021-06-04 09:13 UTC, AlanGriffiths requested changes
I'll PR an alternative approach.

2021-06-04 09:13 UTC, AlanGriffiths commented on src/wayland/wayland_base.cpp
>  #if (WAYLAND_VERSION_MAJOR > 1 || (WAYLAND_VERSION_MAJOR == 1 && WAYLAND_VERSION_MINOR > 16))
Maybe not in this PR, but I think we can drop this backwards-compatibility hack. We no longer target 16.04/core16

2021-06-04 09:13 UTC, AlanGriffiths commented on include/wayland/mir/wayland/wayland_base.h
>  void internal_error_processing_request(wl_client* client, char const* method_name);
The naming and functionality of these functions seems a bit unclear:

1. the "internal" function calls the not-"internal" function, it is usually the other way around.
2. everywhere we call `post_implementation_error()`, we also log the error (which is the difference in functionality)

It looks to me that the _only_ reason for `post_implementation_error()` to exist is the absence of an active exception when called from `WindowWlSurfaceRole::surface_destroyed()`.

2021-06-04 10:16 UTC, RAOF commented on src/server/frontend_wayland/window_wl_surface_role.cpp
> +        wayland::post_implementation_error(
This is not an implementation error; this is a client protocol violation, right?

2021-06-04 16:20 UTC, wmww commented
Superseded by #2057

2021-06-09 15:46 UTC, AlanGriffiths commented
> Superseded by #2057

2021-06-09 15:46 UTC, closed without merging