Add stream operator for miral::Window
MirServer/mir pull request #2071
Opened 2021-06-17 18:21 UTC by wmww

This makes window's correctly appear in test failures, and may have other uses. https://github.com/google/googletest/issues/1149 explains why the stream operators really need to be declared in the same place as the class. I tried a number of other ways, and this is the only one I found to be successful.

2021-06-17 19:30 UTC, AlanGriffiths commented on include/miral/miral/window.h
> +auto operator<<(std::ostream& stream, const miral::Window& window) -> std::ostream&;
We use right const around here!

2021-06-17 19:30 UTC, AlanGriffiths commented on src/miral/window.cpp
> +auto miral::operator<<(std::ostream& stream, const miral::Window& window) -> std::ostream&
We use right const around here!

2021-06-17 19:31 UTC, AlanGriffiths approved these changes
Sure

2021-06-18 11:17 UTC, AlanGriffiths commented
CI say: "You need to add `miral::operator<<(std::basic_ostream<char, std::char_traits<char> >&, miral::Window const&)` to the symbols"

2021-06-18 16:14 UTC, wmww commented on include/miral/miral/window.h
> +auto operator<<(std::ostream& stream, const miral::Window& window) -> std::ostream&;
Oop

2021-06-18 16:27 UTC, wmww commented
Hmm looks like GitHub is broken

2021-06-19 02:29 UTC, wmww commented
I'm going to interpret "Sure" + approval as a bors delegate

bors r=AlanGriffiths

2021-06-21 09:39 UTC, AlanGriffiths commented
> I'm going to interpret "Sure" + approval as a bors delegate

Fair enough. (I'm not really convinced this is a widely useful streaming operator, nor that it has to be declared outside the test framework, but it is relatively harmless.)

2021-06-23 16:13 UTC, wmww commented
> I'm not really convinced this is a widely useful streaming operator, nor that it has to be declared outside the test framework

I can't say it has to be, but I put a bit of work into trying different things and this is the only one I found to actually work.

bors r=AlanGriffiths

2021-06-24 14:47 UTC, AlanGriffiths commented
OK, so the reason this is problematic is that in the `MIRAL_3.0` stanza of the version script (symbols.map) there's a wildcard that matches the new operator:
```plain
    miral::operator*;
```
Currently, that corresponds to:
```
miral::operator<(miral::Window const&, miral::Window const&)
miral::operator==(miral::Output::PhysicalSizeMM const&, miral::Output::PhysicalSizeMM const&)
miral::operator==(miral::Window const&, miral::Window const&)
miral::operator==(miral::Window const&, std::shared_ptr<mir::scene::Surface> const&)
miral::operator==(std::shared_ptr<mir::scene::Surface> const&, miral::Window const&)
```
So these need to be pulled in unambiguously (e.g. by using the mangled names).

2021-06-24 15:27 UTC, wmww commented
@RAOF Alan mentioned to may know some secret of escaping characters in symbols.map?

2021-06-24 16:59 UTC, AlanGriffiths requested changes
Having poked around a bit I can't find a simple way to find this operator at the point of instantiation.

OTOH I think it would be better to provide a `PrintTo()` function for gtest, not a streaming operator that might be confused with something useful. That is, in `miral/window.h`:

```c++
// For Google test
void PrintTo(Window const& window, std::ostream* out);
```

2021-06-25 14:27 UTC, AlanGriffiths commented
Closing in favour of #2081

2021-06-25 14:27 UTC, closed without merging