Improve event builder names
MirServer/mir pull request #2084
Opened 2021-06-28 11:57 UTC by AlanGriffiths

We already broke ABI, so now is a good time

2021-06-28 15:10 UTC, wmww requested changes
Just formatting

2021-06-28 15:10 UTC, wmww commented on include/client/mir/events/event_builders.h
> +                            std::string const& layout, std::string const& variant, std::string const& options);
Good time to also use current formatting?

2021-06-28 15:10 UTC, wmww commented on src/server/input/surface_input_dispatcher.cpp
> +                                                      );
lol

2021-06-28 17:39 UTC, wmww requested changes
More formatting

2021-06-28 17:39 UTC, wmww commented on src/client/events/event_builders.cpp
> +                                         int scan_code, MirInputEventModifiers modifiers)
More formatting needed in this file

2021-06-28 17:39 UTC, wmww commented on src/server/input/validator.cpp
> +                                                       ));
And here

2021-06-28 17:39 UTC, wmww commented on src/server/scene/surface_event_source.cpp
> +                                         ));
And here

2021-06-29 00:02 UTC, wmww approved these changes
bors delegate+

2021-06-29 09:14 UTC, AlanGriffiths commented
bors r=wmww

2021-06-29 09:58 UTC, merged