Catch exception setting keymap in MirAL
MirServer/mir pull request #2099
Opened 2021-07-02 16:50 UTC by wmww

Fixes #2098. I'm not sure exactly how the deadlock was happening, but this prevents it.

2021-07-02 17:01 UTC, AlanGriffiths requested changes
I think this is in the wrong place doing the wrong thing.

What I would expect, is that the exception /1/ propagates to `run_with()` and /2/ the program exits with an error code.

2021-07-05 14:00 UTC, AlanGriffiths commented
I understand why this isn't behaving as I expect: the keymap doesn't fail when set during initialization, it fails when the keyboard device is added.

We should be detecting the problem earlier.

2021-07-05 15:25 UTC, AlanGriffiths requested changes
I think the least bad place to handle the exception is in `device_added()` and have proposed that as #2103.

But that's only dealing with part of the problem. We should detect and report the bad configuration option before a device is plugged in and trying to apply it.

2021-07-06 18:25 UTC, wmww commented
Superseded by #2103

2021-07-06 18:25 UTC, closed without merging