Virtual keyboard protocol
MirServer/mir pull request #2111
Opened 2021-07-08 23:18 UTC by wmww

Closes #2063. Includes a bunch of stuff that will land in individual PRs before this one is marked ready.

To test:
- Run mir something like this:
```
WAYLAND_DISPLAY=mir ./bin/miral-shell --add-wayland-extensions='zwlr_layer_shell_v1:zwp_virtual_keyboard_manager_v1'
```
- Run squeekboard on Mir
```
WAYLAND_DISPLAY=mir squeekboard
```
- Show the OSK using a D-Bus message
```
busctl call --user sm.puri.OSK0 /sm/puri/OSK0 sm.puri.OSK0 SetVisible b true
```
Type into a window!

I still need to look into how to make automatic show/hide work

2021-07-09 08:24 UTC, AlanGriffiths commented
> I still need to look into how to make automatic show/hide work

There must be a request from the client when focus goes to text input, and something decides if OSK is needed. But is that something Mir? Or bespoke in the shell? Or a service?

For some usecases, just having the OSK on always is enough. For others a swipe-up gesture.

2021-07-09 09:17 UTC, RAOF commented
> > I still need to look into how to make automatic show/hide work
> 
> There must be a request from the client when focus goes to text input, and something decides if OSK is needed. But is that something Mir? Or bespoke in the shell? Or a service?

Hey, aren't you meant to be on holiday 😛.

I'm reasonably sure that's [text-input](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/blob/main/unstable/text-input/text-input-unstable-v3.xml) + [input-method](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/blob/main/unstable/input-method/input-method-unstable-v1.xml)

2021-07-12 18:08 UTC, wmww commented
> I'm reasonably sure that's text-input + input-method

That's what I'm hoping

2021-07-23 10:29 UTC, AlanGriffiths commented
A small note about squeekboard it isn't in 20.04 archives, but is in 21.04 on:

```plain
$ rmadison squeekboard
 squeekboard | 1.12.0-1 | hirsute/universe | source, amd64, arm64, armhf, ppc64el, riscv64, s390x
 squeekboard | 1.12.0-1 | impish/universe  | source, amd64, arm64, armhf, ppc64el, riscv64, s390x
```

2021-07-23 16:57 UTC, AlanGriffiths requested changes
A couple of small things. Seems to work.

And, seemingly, we could do a Frame snap with a "fixed" OSK. (Just not "on demand".)

2021-07-23 16:57 UTC, AlanGriffiths commented on src/server/frontend_wayland/virtual_keyboard_v1.cpp
> +    id++;
This could simply be an atomic `next_id` with `fetch_add(1)` with no need for a mutex.

2021-07-23 16:57 UTC, AlanGriffiths commented on src/wayland/symbols.map
> +MIRWAYLAND_2.2.2 {
This should match the Mir release: MIRWAYLAND_2.5

2021-07-24 01:07 UTC, wmww commented
In a possibly controversial change, I've decided we should stop sticking "manager" on the end of protocol names. Can revert last commit if you think it's very important that protocols have the same name as their globals. Seems like code noise to me.

2021-07-26 09:08 UTC, AlanGriffiths approved these changes
LGTM

bors r+

2021-07-26 09:11 UTC, AlanGriffiths commented
> I've decided we should stop sticking "manager" on the end of protocol names

Yeah, not sure how we started that. Likely an accident.

2021-07-26 09:32 UTC, merged