Add resync keyboard event
MirServer/mir pull request #2146
Opened 2021-08-16 23:59 UTC by wmww

This creates a new `MirResyncKeyboardEvent` and a new event dispatcher that fires it when the server starts. This replaces the resync system that was added in  #1035. If this works (which it does on my machine), #999 should stay fixed.

2021-08-17 09:39 UTC, AlanGriffiths requested changes
Needs tests

2021-08-17 09:39 UTC, AlanGriffiths commented on src/server/input/resync_keyboard_dispatcher.h
> +class ResyncKeyboardDispatcher : public InputDispatcher
Having `ResyncKeyboardDispatcher` and `KeyRepeatDispatcher` as separate transformations might be seen as adding to the profusion of objects that makes the Mir codebase hard to approach. But having thought about it I think this is right as they can be tested (or even used) independently.

2021-08-18 09:02 UTC, AlanGriffiths approved these changes
bors r+

2021-08-18 09:02 UTC, AlanGriffiths commented
Oops!

bors r-

2021-08-18 09:11 UTC, AlanGriffiths commented on src/common/symbols.map
> +} MIR_COMMON_2.5;
FTFY

bors r+

2021-08-18 09:51 UTC, merged

2021-08-18 21:07 UTC, wmww commented on src/common/symbols.map
> +} MIR_COMMON_2.5;
How do you know the current version of mircommon? `src/common/CMakeLists.txt` has no clues, except that the ABI is version 8.

2021-08-19 16:49 UTC, AlanGriffiths commented on src/common/symbols.map
> +} MIR_COMMON_2.5;
As you say, the ABI version of `mircommon` is 8.

The release of Mir with which these symbols will be introduced to `mircommon` 8 is 2.5, so the stanza is called `MIR_COMMON_2.5`.