Refactor KeybaordHelper out of WlKeyboard
MirServer/mir pull request #2151
Opened 2021-08-20 18:04 UTC by wmww

One of the initially unimplemented components of the input method protocol is keyboard grabs. Squeekboard doesn't grab the keybaord, but CJK input methods (such as [wlanthy](https://github.com/st3r4g/wlanthy) do need to. `zwp_input_method_keyboard_grab_v2` is a separate interface than `wl_keyboard` and will need a separate implementation, but requires much of the same functionality.

After several attempts involving inheritance, I settled on a more composition-oriented approach. `KeybaordHelper` implements the common keyboard logic, and calls into `KeyboardImpl` to send events. In this PR `WlKeyboard` is the only `KeyboardImpl`, but an upcoming PR will add a new grab keybaord implementation.

2021-08-23 14:41 UTC, AlanGriffiths commented
This builds on the changes that appear to be the cause of #2150 - let's not merge until we've addressed that.

2021-09-02 23:22 UTC, wmww commented
This is now ready for review again

2021-09-06 11:18 UTC, AlanGriffiths requested changes
It took me two passes to understand how this fits together. With that understanding it does make sense, but I wonder how we can make it easier to understand.

I've made some suggestions that I hope would have helped me.

Other opinions invited!

2021-09-07 19:11 UTC, wmww commented on src/server/frontend_wayland/keyboard_helper.h
> +class KeyboardHelper
`KeyboardImpl` too contentious, how about `KeyboardHelper` and `KeyboardCallbacks`?

2021-09-07 19:17 UTC, wmww commented on src/server/frontend_wayland/wl_seat.cpp
> +
And also `seat`, but yes. There could be getters on `WlSeat` for all of them, but I thought it cleaner and more maintainable to make `WlSeat` responsible for creating keyboard helpers.

2021-09-07 19:22 UTC, wmww commented on src/server/frontend_wayland/keyboard_helper.cpp
> + * Copyright © 2018-2019 Canonical Ltd.
Fixed

2021-09-07 19:22 UTC, wmww commented on src/server/frontend_wayland/keyboard_helper.h
> +#define MIR_FRONTEND_BASIC_WL_KEYBOARD_H
Fixed

2021-09-07 19:23 UTC, wmww commented on src/server/frontend_wayland/keyboard_helper.h
> +class KeyboardHelper
Changed name and used private inheritance

2021-09-08 11:26 UTC, AlanGriffiths approved these changes
Still not convinced by `KeyboardHelper`, maybe `KeyboardEventHandler`? But won't block.

bors d+

2021-09-08 17:12 UTC, wmww commented
Hmm, `KeyboardEventHandler` seems just as nonspecific as `KeyboardHelper` to me. There might be a better name out there, but I haven't thought of it yet.

bors r+

2021-09-08 17:47 UTC, merged