Change extension names to alwyas match global names
MirServer/mir pull request #2210
Opened 2021-11-04 21:40 UTC by wmww

Fixes #2208. Extension names are now automatically deduced for built-in extensions, and if a bespoke extension with an invalid name is enabled, a fatal error is raised at startup.

2021-11-05 09:47 UTC, AlanGriffiths requested changes
This does add consistency but, unless I miss something, it breaks existing configurations:

Suppose a Mir based system (mir-kiosk say) is deployed and the `.config` says:
```
add-wayland-extension=foo_master
```

With the change of `foo_master` to `foo` that is no longer going to work. There needs to be a way to support configurations with the legacy names.

NB In addition to the real possibilies of mir-kiosk `.config` files and `ubuntu-frame` snap configuration options which we might reasonably migrate with text substitution outside Mir itself there is also the theoretical option of command-line parameters in a runner script.

Hence, I think the best approach is to "translate" any legacy names in `parse_extensions_option()`.

2021-11-05 16:41 UTC, wmww commented
That sounds reasonable. Note that this would not effect extensions turned on by shells, but hopefully they were using our helper variables in which case they'll be fine.

2021-11-05 17:03 UTC, AlanGriffiths commented
> That sounds reasonable. Note that this would not effect extensions turned on by shells, but hopefully they were using our helper variables in which case they'll be fine.

Yep. I don't think we have enough downstreams to worry about that level of idiot proofing. (Unless you have a neat idea that caters for them too.)

2021-11-09 10:17 UTC, AlanGriffiths approved these changes
bors r+

2021-11-09 10:17 UTC, AlanGriffiths commented on src/miral/wayland_extensions.cpp
> +};
[Non blocking]

I'm probably old fashioned, but it seems odd to use `map<>` for such small N. A couple of `if ... else if ...` conditions would avoid all the non-constinit setup and teardown.

2021-11-09 10:43 UTC, merged