Send wl_pointer.axis_stop
MirServer/mir pull request #2275
Opened 2022-01-13 03:11 UTC by wmww

This sends a `wl_pointer.axis_stop` event when we get a libinput scroll event that has an axis with value 0. Reading the llibinput and Wayland docs it seems to be correct behavior, is consistent with both Weston and wlroots and works with Firefox.

I've quite possibly screwed up the symbols, so double check them.

Fixes #2247, fixes #2276

2022-01-13 03:19 UTC, wmww commented
Fixes #2276

2022-01-13 08:06 UTC, Saviq commented
```plain
[----------] 3 tests from LibInputDeviceOnTouchpad
[ RUN ] LibInputDeviceOnTouchpad.process_event_handles_scroll
unknown file: Failure

Unexpected mock function call - returning directly.
Function call: handle_input(@0x7ffd85ca5330 16-byte object <80-10 CE-03 00-00 00-00 C0-91 DD-03 00-00 00-00>)
Google Mock tried the following 2 expectations, but none matched:

/spread/mir/tests/unit-tests/input/evdev/test_libinput_device.cpp:771: tried expectation #0: EXPECT_CALL(mock_sink, handle_input(mt::PointerAxisChange(mir_pointer_axis_vscroll, -10.0f)))...
Expected: all pre-requisites are satisfied
Actual: the following immediate pre-requisites are not satisfied:
/spread/mir/tests/unit-tests/input/evdev/test_libinput_device.cpp:769: pre-requisite #0
(end of pre-requisites)
Expected: to be called once
Actual: never called - unsatisfied and active
/spread/mir/tests/unit-tests/input/evdev/test_libinput_device.cpp:774: tried expectation #1: EXPECT_CALL(mock_sink, handle_input(mt::PointerAxisChange(mir_pointer_axis_hscroll, 1.0f)))...
Expected arg #0: pointer axis change (3, 1)
Actual: 16-byte object <80-10 CE-03 00-00 00-00 C0-91 DD-03 00-00 00-00>
Expected: to be called once
Actual: never called - unsatisfied and active
unknown file: Failure

Unexpected mock function call - returning directly.
Function call: handle_input(@0x7ffd85ca5330 16-byte object <80-10 CE-03 00-00 00-00 C0-91 DD-03 00-00 00-00>)
Google Mock tried the following 2 expectations, but none matched:

/spread/mir/tests/unit-tests/input/evdev/test_libinput_device.cpp:771: tried expectation #0: EXPECT_CALL(mock_sink, handle_input(mt::PointerAxisChange(mir_pointer_axis_vscroll, -10.0f)))...
Expected arg #0: pointer axis change (2, -10)
Actual: 16-byte object <80-10 CE-03 00-00 00-00 C0-91 DD-03 00-00 00-00>
Expected: to be called once
Actual: never called - unsatisfied and active
/spread/mir/tests/unit-tests/input/evdev/test_libinput_device.cpp:774: tried expectation #1: EXPECT_CALL(mock_sink, handle_input(mt::PointerAxisChange(mir_pointer_axis_hscroll, 1.0f)))...
Expected: all pre-requisites are satisfied
Actual: the following immediate pre-requisites are not satisfied:
/spread/mir/tests/unit-tests/input/evdev/test_libinput_device.cpp:772: pre-requisite #0
(end of pre-requisites)
Expected: to be called once
Actual: never called - unsatisfied and active
/spread/mir/tests/unit-tests/input/evdev/test_libinput_device.cpp:769: Failure
Actual function call count doesn't match EXPECT_CALL(mock_builder, pointer_axis_event(mir_pointer_axis_source_finger, ***time_stamp_1***, mir_pointer_action_motion, 0, 0, 0, 0.0f, -10.0f, 0.0f, 0.0f))...
Expected: to be called once
Actual: never called - unsatisfied and active
/spread/mir/tests/unit-tests/input/evdev/test_libinput_device.cpp:772: Failure
Actual function call count doesn't match EXPECT_CALL(mock_builder, pointer_axis_event(mir_pointer_axis_source_finger, ***time_stamp_2***, mir_pointer_action_motion, 0, 0, 0, 1.0f, 0.0f, 0.0f, 0.0f))...
Expected: to be called once
Actual: never called - unsatisfied and active
/spread/mir/tests/unit-tests/input/evdev/test_libinput_device.cpp:771: Failure
Actual function call count doesn't match EXPECT_CALL(mock_sink, handle_input(mt::PointerAxisChange(mir_pointer_axis_vscroll, -10.0f)))...
Expected: to be called once
Actual: never called - unsatisfied and active
/spread/mir/tests/unit-tests/input/evdev/test_libinput_device.cpp:774: Failure
Actual function call count doesn't match EXPECT_CALL(mock_sink, handle_input(mt::PointerAxisChange(mir_pointer_axis_hscroll, 1.0f)))...
Expected: to be called once
Actual: never called - unsatisfied and active
[ FAILED ] LibInputDeviceOnTouchpad.process_event_handles_scroll (2 ms)
```

2022-01-13 10:32 UTC, AlanGriffiths requested changes
A few ABI management issues.

2022-01-13 10:32 UTC, AlanGriffiths commented on src/common/symbols.map
> +  mir_pointer_event_axis_stop;
Should be in a 2.7 stanza

2022-01-14 11:04 UTC, AlanGriffiths approved these changes
LGTM

bors r+

2022-01-14 11:32 UTC, merged