More cruft identified by CLion
MirServer/mir pull request #2287
Opened 2022-01-19 17:15 UTC by AlanGriffiths

2022-01-19 21:40 UTC, wmww requested changes

2022-01-19 21:40 UTC, wmww commented on src/server/input/key_repeat_dispatcher.cpp
>  // Returns true if the original event has been handled, that is ::dispatch should not pass it on.
Comment is no longer applicable

2022-01-19 21:41 UTC, wmww commented on tests/mir_test_doubles/CMakeLists.txt
> +        ${PROJECT_SOURCE_DIR}/tests/include/mir/test/doubles/mock_console_services.h
indentation

2022-01-20 08:46 UTC, AlanGriffiths commented on src/server/input/key_repeat_dispatcher.cpp
>  // Returns true if the original event has been handled, that is ::dispatch should not pass it on.
It was never applicable, but gone now

2022-01-20 15:47 UTC, wmww approved these changes
bors r+

2022-01-20 16:19 UTC, merged