Modernize surface observer
MirServer/mir pull request #2371
Opened 2022-03-29 23:55 UTC by wmww

This updates the surface observer to use the new observer system. Some changes are needed to allow safely moving the observation calls between threads (such as using a shared pointer instead of raw pointer to events). There's still some bits to finish and crashes/deadlocks to sort out before it's ready to merge.

2022-03-30 02:02 UTC, wmww commented
Problem: Object has a mutex, and creates Observer. Object wants to both receive notifications from Observer, and unregister Observer. Object is locked during both of these things. With the current guarantees of observers, this must cause a deadlock.

1. Thread A: Object method called
1. Thread A: Object locks
1. Thread B: Observer work runs (spawned previously from different 
1. Thread B: Observer locks
1. Thread B: Object method called
1. Thread B: Object tries to lock, blocked
1. Thread A: Object calls `unregister_interest()`
1. Thread A: Observer tried to lock, blocked

NOTE:
- `unregister_interest()` is not allowed to return before the observer methods have all finished
- The observer threads can't finish until the object is unlocked

We previously got around something similar with a recursive mutex, but that doesn't help when instead of wanting to unregister from a notification, you simply happen to try to unregister at the same time as a notification. I think I might be hitting a somewhat more solvable variant of this problem in practice (trying to unregister a *different* observer while one is sending a notification), but I'd like a solution that doesn't leave less likely but possible deadlocks lurking.

Perhaps we should be using `mir::LockableCallback` to lock Object's mutex before the observer is locked?

2022-03-30 06:05 UTC, RAOF commented
Hm, yes.

There are two broad classes of solutions here:
* Ensure locks are always taken in the same order (`mir::LockableCallback` implements this pattern), or
* *Don't take locks*, and serialise things by only ever doing stuff on one thread (which the `Executor` infrastructure can provide)

We can't use `mir::LockableCallback` for this, as the Observer object is the thing that gets notified, but we could do something similar. I think `WeakObserver.lock()` would just need to call `Observer->lock()` before taking its own lock.

I think we could even use SFINAE to make the `lock` method optional on `Observer`? Maybe we don't want to?

2022-04-28 23:26 UTC, wmww commented
This includes several changes to the miroil headers. Perhaps I should be keeping those stable?

2022-04-29 09:03 UTC, AlanGriffiths requested changes
It isn't clear from first impression whether all the test changes are syntactic - I need to come back to that.

Otherwise, some nitpicking and questions.

And yes, it would be better to preserve the miral API (and ABI).

2022-04-29 14:57 UTC, wmww commented
> And yes, it would be better to preserve the miral API (and ABI).

I'm talking about the mirOIL API (I suspect you mistyped, but wanted to clarify in case you misread)

2022-04-29 15:51 UTC, AlanGriffiths commented on src/server/compositor/stream.h
> +#include <atomic>
Yeah, that nonsense is what led me to the "drive by" cleanup PR earlier,

2022-05-26 10:58 UTC, AlanGriffiths approved these changes
bors merge

2022-05-26 12:04 UTC, Saviq commented
There's a bunch of test failures in random configurations…

On both alpines:
```plain
	 53 - mir_integration_tests.SurfaceStackCompositor.* (Failed)
```

On fedora it killed the compiler…

On others:
```plain
	 45 - wlcs.Gravity/XdgPopupPositionerTest.* (ILLEGAL)
	 26 - wlcs.Layer/LayerSurfaceLayerTest.* (Failed)
```

2022-05-26 13:09 UTC, AlanGriffiths commented
Random test failures are problematic. Let's get a few more data points in the hope of a pattern emerging

bors try

2022-05-26 14:15 UTC, AlanGriffiths commented
> Somewhat consistent, then:

Yes. Given the scale of this change I suspect there's been a non-obvious break to the synchronization guarantees that breaks assumptions made in code using it.

2022-07-08 20:26 UTC, wmww commented
Ah! The problem seems to be a `SurfaceStack` race condition

2022-08-01 10:59 UTC, AlanGriffiths approved these changes
bors merge

2022-08-01 11:04 UTC, AlanGriffiths commented
Oops! Forgot this wasn't targeting main

2022-08-02 16:51 UTC, wmww commented
(had to manually trigger CI for some reason)

2022-08-03 11:15 UTC, AlanGriffiths approved these changes
bors merge

2022-08-03 14:49 UTC, AlanGriffiths commented
bors retry

2022-08-03 16:50 UTC, AlanGriffiths commented
bors retry

2022-08-03 17:16 UTC, merged