[build]: Remove unnecessary files from release tarballs.
MirServer/mir pull request #2441
Opened 2022-05-26 04:40 UTC by RAOF

There's no need for our release tarballs to contain a `debian/`
directory, or the GitHub CI metadata.

I'm *pretty* sure that GitHub will respect the git attributes when
generating the tarball.

2022-05-26 12:07 UTC, Saviq requested changes
There's probably more that we could clean up?

```plain
$ unzip -l mir-clean-up-release-tarballs.zip | grep -e debian -e git
      225  2022-05-26 06:40   mir-clean-up-release-tarballs/.gitignore
        0  2022-05-26 06:40   mir-clean-up-release-tarballs/.gitmodules
        0  2022-05-26 06:40   mir-clean-up-release-tarballs/debian/
```

2022-06-01 14:30 UTC, Saviq commented
How clean do we want it?

These irk me:
```
bors.toml
spread/**
tools/make_release_tarball
tools/ppa-upload.sh
tools/process_snaps.py
tools/requirements.txt
```

Should they be moved around so that the proposed .gitattributes will cover? Should they be excluded explicitly? Should they stay around?

2022-06-03 09:49 UTC, RAOF commented on .gitattributes
> +.github/*      export-ignore
Hmmmm, yeah. I seem to recall it not working like that before, but maybe I was holding it wrong? 🤷‍♀️

2022-06-03 14:16 UTC, Saviq approved these changes
Yup.

bors merge

2022-06-03 14:43 UTC, merged