Fix #2607 modification of logind source
MirServer/mir pull request #2611
Opened 2022-09-01 18:15 UTC by graysonguarino

Fixes #2607. I believe this should tackle it as I cannot reproduce the error now, but this should be double-checked by someone who faces this bug.

2022-09-02 05:55 UTC, Saviq commented on src/server/console/CMakeLists.txt
>    logind-session.c                          logind-session.h
These should go away, then? Are they even used? If we treat them the same as wayland protocols, we shouldn't have those checked in at all, but instead rely on the generated ones.

2022-09-02 15:04 UTC, AlanGriffiths requested changes
Mostly good. Just remove the files that should never have been in source control from source control

2022-09-02 15:04 UTC, AlanGriffiths commented on src/server/console/CMakeLists.txt
> -  logind-session.c                          logind-session.h
These files should also be removed from git

2022-09-06 16:40 UTC, AlanGriffiths commented
```plain
$ git diff
diff --git a/tests/unit-tests/CMakeLists.txt b/tests/unit-tests/CMakeLists.txt
index 1a478a82b2..de841283dc 100644
--- a/tests/unit-tests/CMakeLists.txt
+++ b/tests/unit-tests/CMakeLists.txt
@@ -32,6 +32,7 @@ include_directories(
   ${PROJECT_SOURCE_DIR}/src/include/gl
   ${PROJECT_SOURCE_DIR}/src/platforms/common/client
   ${PROJECT_SOURCE_DIR}/src/platforms/common/server
+  ${CMAKE_BINARY_DIR}/src/server/console
   ${GLIB_INCLUDE_DIRS}
   ${GIO_INCLUDE_DIRS}
 )
```

2022-09-06 16:57 UTC, AlanGriffiths commented on src/server/console/CMakeLists.txt
> +  ${CMAKE_CURRENT_BINARY_DIR}/src/server/console
This _was_ right before the last commit

2022-09-06 17:03 UTC, AlanGriffiths commented
@graysonguarino

1. Revert or drop the last commit
2. Copy the above patch to the clipboard
3. In Clion: Git/Patch/Apply patch from Clipboard
4. Build locally
5. Commit & push

2022-09-07 09:13 UTC, AlanGriffiths approved these changes
LGTM

@Saviq WDYT?

2022-09-07 13:36 UTC, Saviq approved these changes
Yup!

bors r=AlanGriffiths,Saviq

2022-09-07 14:12 UTC, AlanGriffiths commented
bors retry

2022-09-07 14:59 UTC, merged