Bind shm textures when we create the buffers
MirServer/mir pull request #2621
Opened 2022-09-06 14:21 UTC by AlanGriffiths

Possibly inefficient (if we never need to upload), but fixes #2620

(Pushed for discussion)

2022-09-06 14:49 UTC, AlanGriffiths commented
Our existing logic only uploads shm textures once we try to composite the buffers. That leaves us open to the client deleting the shm buffer before we use it.

Always uploading the texture as proposed here closes down that opportunity, but is unnecessary for hidden, offscreen or occluded surfaces.

I don't see a simple way to resolve this conflict

2022-09-06 15:35 UTC, AlanGriffiths commented
I'll also mention #2594 here, but as RAOF sees that without the "Wayland buffer destroyed before use; rendering will be incomplete" log entries it is probably something different

2022-09-06 23:56 UTC, RAOF commented
As per [the protocol]():
> Destroying the wl_buffer after wl_buffer.release does not change the surface contents. Destroying the wl_buffer before wl_buffer.release is allowed as long as the underlying buffer storage isn't re-used (this can happen e.g. on client process termination). However, if the client destroys the wl_buffer before receiving the wl_buffer.release event and mutates the underlying buffer storage, the surface contents become undefined immediately.

It appears that we need to handle `wl_buffer` lifetimes slightly differently. This applies to both SHM buffers and hardware buffers, so we should audit our lifecycle handling of both.

2022-09-07 05:34 UTC, Saviq commented
It also didn't work, very well, here.
![frame_2022-09-07T07:33+02:00](https://user-images.githubusercontent.com/231077/188796704-44661119-3927-46cf-8cac-5ae9b937f9f9.png)

2022-09-07 05:39 UTC, Saviq commented
Also crashes when hovering those ghosts:

[gdb.txt](https://github.com/MirServer/mir/files/9502979/gdb.txt)

2022-09-07 09:28 UTC, AlanGriffiths commented
> As per [the protocol](https://gitlab.freedesktop.org/wayland/wayland/-/blob/main/protocol/wayland.xml#L1464):

Thanks for looking up the reference!

> It appears that we need to handle `wl_buffer` lifetimes slightly differently. This applies to both SHM buffers and hardware buffers, so we should audit our lifecycle handling of both.

Yes, and I suspect there's other work needed in this (compositing/scenegraph) area. Better tracking of obscuration and tracking of damage as examples.

2022-09-07 10:04 UTC, Saviq commented
> Weird. Is that a #2614 like artefact? (Might be worth pulling that in too)

This was a single output (as per my screenshot), but a similar visual, yeah. Will try.

2022-09-12 13:47 UTC, AlanGriffiths commented
This would be better with an egl fence, but Chris has volunteered to fix that later.

2022-09-14 08:11 UTC, RAOF requested changes
I *think* this is still racy as-is.

Looking more over the Wayland server API, I think the way to do this *almost* properly is to:
1. Get the data pointer up-front in the constructor with `wl_shm_buffer_get_data`
2. Get an explicit reference to the `wl_shm_pool` with `wl_shm_buffer_ref_pool`. This will (should!) ensure the backing store stays around, even if the `wl_buffer` is destroyed
3. When we `bind()`, do what we're doing now if `buffer.lock()` works, but if it *doesn't* (ie: the buffer has already been destroyed), we (3a) should just use the already-stored pointer
4. In the destructor, `wl_shm_pool_unref`

The small problem here is at (3a): If the client lied about the buffer, we can SIGBUS when trying to read out of the pointer, and `wl_shm_{begin,end}_access` will not (but *almost* will) work.

I guess we could just install our own SIGBUS handler here?

2022-09-14 08:19 UTC, RAOF commented
The alternative to installing our own `SIGBUS` handler here is to fix libwayland. It is *almost* possible to just hold on to the `wl_shm_buffer`, even once the underlying buffer has gone away (as long as you hold a ref on the underlying `shm_pool`). The *only* problem is if `wl_shm_buffer_end_access` needs to send an error!

2022-09-14 08:31 UTC, AlanGriffiths commented on src/platforms/common/server/buffer_from_wl_shm.cpp
> +                auto const mapping = map_readable();
You're right. (That was my latest "improvement", I shall revert that.)

With that I think we can land while continuing to look at the further rework you describe.

2022-09-14 08:42 UTC, RAOF commented on src/platforms/common/server/buffer_from_wl_shm.cpp
> +                auto const mapping = map_readable();
+1 on that

2022-09-15 02:35 UTC, RAOF approved these changes
Yup. It's inelegant, and there's (hopefully) a better way coming, but this is an improvement for now.

bors r+

2022-09-15 04:38 UTC, RAOF commented
Bors failure looks transient(?)

bors r+

2022-09-15 05:09 UTC, merged