platform/buffer_from_wl_shm: Handle clients immediately destroying the buffer
MirServer/mir pull request #2645
Opened 2022-09-16 08:10 UTC by RAOF

We need to handle clients destroying the wl_buffer after commit. This is legal, as long as the backing store is not invalidated.

Unfortunately, clients can create a buffer from the wl_shm_pool and then immediately destroy the wl_shm_pool. This is also valid.

So in order to prevent the backing store from being invalidated we need to take a reference on the wl_shm_pool backing our shm_buffer.

However!

If we have a reference on the wl_shm_pool, attempts to resize it will fail. Real clients do this, so we can't universally take a reference to the pool.

Instead, we take a reference to the pool (and the buffer offset into it) when the buffer is being destroyed. This way only clients that do the commit/delete dance have their shm_pools frozen, and *those* clients will normally delete their shm_pools immediately anyway.

2022-09-16 08:13 UTC, RAOF commented
Marking this as no-merge as it *currently* allows a client that submits a bad buffer and then deletes it to crash Mir.

We need to add a SIGBUS handler to fix that. We can't use libwayland's wl_shm_buffer_{begin/end}, as *they* crash in the same circumstance.

2022-09-16 09:59 UTC, AlanGriffiths approved these changes
This looks mostly right with the caveat about badly behaved clients...

> We need to add a SIGBUS handler to fix that. We can't use libwayland's wl_shm_buffer_{begin/end}, as _they_ crash in the same circumstance.

This could be an "interesting" exercise.

Signals and multithreaded programs are problematic: any SIGBUS signal need not related to this thread. And we already have a "dance" around libwayland's SIGBUS handler and ours in `mir::run_mir()`.

2022-09-16 09:59 UTC, AlanGriffiths commented on src/platforms/common/server/buffer_from_wl_shm.cpp
> +                            * TODO: Replace with fences
Note there is a `glFinish()` in `upload_to_texture()`

2022-09-20 07:16 UTC, RAOF commented
This should now be good to go. Miriway runs locally without (this kind of) error, wlcs passes the bad buffer tests.

2022-09-27 03:00 UTC, RAOF commented
Argh, bollocks. This is still broken - the failure path might call `wl_resource_send_error` from a non-Wayland-mainloop thread.

2022-12-05 04:40 UTC, RAOF commented
The WLCS test failure requires https://github.com/MirServer/wlcs/pull/253 to land

2022-12-05 17:07 UTC, Saviq commented
Kicked to refresh from main

2022-12-05 17:25 UTC, Saviq commented
Looks like the dispmanx platform didn't get the right treatment…

2022-12-06 08:38 UTC, Saviq commented
Apart from the wlcs failures looks like we're pushing qemu again…

```plain
 qemu: uncaught target signal 11 (Segmentation fault) - core dumped
/<<PKGBUILDDIR>>/tools/detect_fd_leaks.bash: line 84: 63788 Segmentation fault      (core dumped) $@ 2>&1
     63789 Done                    | detect_fd_leaks
```

2022-12-06 14:13 UTC, AlanGriffiths commented
Weirdly, building on 22.10 I see #2527 (even with precompiled headers switched off)

2022-12-06 17:04 UTC, AlanGriffiths requested changes
Some comments from a first pass...

This is big. On the surface, there seem to be several pieces that could be pulled out for easier review and land separately:

1. SIGBUS changes
2. new shm and shm_backing implementation & tests
3. Stuff moving to better places (e.g. `wl_format_to_mir_format()` -> `DRMFormat::as_mir_format()`)

That still leaves a lot of rework to review, but breaks off some reviewable and landable chunks.

Another thing that makes reviewing hard, is that the commits related to the above are intermingled with each other and with experiments(?) that got dropped. (E.g. `buffer_from_wl_shm.*` gets changed over the first N comments and eventually deleted).

That makes it hard to select a bunch of commits to focus on one area of change without losing track of what has and hasn't been reviewed.

2022-12-07 06:42 UTC, RAOF commented
The wlcs failure requires https://github.com/MirServer/wlcs/pull/255 to land, so that https://github.com/MirServer/wlcs/pull/253 actually results in a new wlcs package in the PPA.

2022-12-07 09:59 UTC, Saviq commented
Looks like one flaky test still:

```plain
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from BadBufferTest
[ RUN      ] BadBufferTest.test_truncated_shm_file
[2022-12-07 09:47:31.381529] <information> mirserver: Starting
[2022-12-07 09:47:31.381636] < - debug - > mirserver: No session management supported
[2022-12-07 09:47:31.381680] <information> VT switch key handler: No VT switching support available: MinimalConsoleServices does not support VT switching
[2022-12-07 09:47:31.381783] <information> mircommon: Loading modules from: /<<PKGBUILDDIR>>/build-amd64/lib/server-modules/
[2022-12-07 09:47:31.381850] <information> mircommon: Loading module: /<<PKGBUILDDIR>>/build-amd64/lib/server-modules/graphics-gbm-kms.so.20
[2022-12-07 09:47:31.381873] <information> mircommon: Loading module: /<<PKGBUILDDIR>>/build-amd64/lib/server-modules/graphics-wayland.so.20
[2022-12-07 09:47:31.381887] <information> mircommon: Loading module: /<<PKGBUILDDIR>>/build-amd64/lib/server-modules/graphics-eglstream-kms.so.20
[2022-12-07 09:47:31.381901] <information> mircommon: Loading module: /<<PKGBUILDDIR>>/build-amd64/lib/server-modules/server-x11.so.20
[2022-12-07 09:47:31.381915] <information> mircommon: Loading module: /<<PKGBUILDDIR>>/build-amd64/lib/server-modules/input-evdev.so.8
[2022-12-07 09:47:31.382661] <information> mircommon: Loading module: /<<PKGBUILDDIR>>/build-amd64/lib/server-modules/graphics-throw.so
[2022-12-07 09:47:31.382701] <information> mircommon: Loading module: /<<PKGBUILDDIR>>/build-amd64/lib/server-modules/graphics-dummy.so
[2022-12-07 09:47:31.382719] <information> mircommon: Loading module: /<<PKGBUILDDIR>>/build-amd64/lib/server-modules/input-stub.so
[2022-12-07 09:47:31.382789] <information> mirserver: Found display driver: mir:stub-graphics (version 2.10.0)
[2022-12-07 09:47:31.382808] <information> mirserver: Driver supports:
[2022-12-07 09:47:31.382820] <information> mirserver: 	System (priority 1)
[2022-12-07 09:47:31.382833] < -warning- > mirserver: Manually-specified display platform mir:stub-graphics does not claim to support this system. Trying anyway...
[2022-12-07 09:47:31.382900] <information> mirserver: Selected display driver: mir:stub-graphics (version 2.10.0)
[2022-12-07 09:47:31.383041] <information> mircommon: Loading modules from: /<<PKGBUILDDIR>>/build-amd64/lib/server-modules/
[2022-12-07 09:47:31.383103] <information> mircommon: Loading module: /<<PKGBUILDDIR>>/build-amd64/lib/server-modules/graphics-gbm-kms.so.20
[2022-12-07 09:47:31.383121] <information> mircommon: Loading module: /<<PKGBUILDDIR>>/build-amd64/lib/server-modules/graphics-wayland.so.20
[2022-12-07 09:47:31.383135] <information> mircommon: Loading module: /<<PKGBUILDDIR>>/build-amd64/lib/server-modules/graphics-eglstream-kms.so.20
[2022-12-07 09:47:31.383148] <information> mircommon: Loading module: /<<PKGBUILDDIR>>/build-amd64/lib/server-modules/server-x11.so.20
[2022-12-07 09:47:31.383161] <information> mircommon: Loading module: /<<PKGBUILDDIR>>/build-amd64/lib/server-modules/input-evdev.so.8
[2022-12-07 09:47:31.383836] <information> mircommon: Loading module: /<<PKGBUILDDIR>>/build-amd64/lib/server-modules/graphics-throw.so
[2022-12-07 09:47:31.383869] <information> mircommon: Loading module: /<<PKGBUILDDIR>>/build-amd64/lib/server-modules/graphics-dummy.so
[2022-12-07 09:47:31.383886] <information> mircommon: Loading module: /<<PKGBUILDDIR>>/build-amd64/lib/server-modules/input-stub.so
[2022-12-07 09:47:31.383929] <information> mirserver: Found rendering driver: mir:stub-graphics (version 2.10.0)
[2022-12-07 09:47:31.383944] <information> mirserver: Driver supports:
[2022-12-07 09:47:31.383957] <information> mirserver: 	System (priority 1)
[2022-12-07 09:47:31.383970] < -warning- > mirserver: Manually-specified rendering platform mir:stub-graphics does not claim to support this system. Trying anyway...
[2022-12-07 09:47:31.384026] <information> mirserver: Selected rendering driver: mir:stub-graphics (version 2.10.0)
[2022-12-07 09:47:31.387174] <information> mirserver: Using software cursor
[2022-12-07 09:47:31.387346] < - ERROR - > : failed to create BasicScreenShooter: ../../../../src/renderers/gl/renderer.cpp(237): Throw in function static GLuint mir::renderer::gl::Renderer::ProgramFactory::compile_shader(GLenum, const GLchar*)
Dynamic exception type: boost::wrapexcept<std::system_error>
std::exception::what: Failed to create shader: GL_NO_ERROR (0)

[2022-12-07 09:47:31.387663] <information> mirserver: Selected input driver: mir:stub-input (version: 2.10.0)
[2022-12-07 09:47:31.387719] <information> mirserver: Mir version 2.10.0
[2022-12-07 09:47:31.388661] <information> mirserver: Initial display configuration:
[2022-12-07 09:47:31.388706] <information> mirserver: * Output 1: VGA connected, used
[2022-12-07 09:47:31.388721] <information> mirserver: . |_ Physical size 0.0" 0x0mm
[2022-12-07 09:47:31.388733] <information> mirserver: . |_ Power is on
[2022-12-07 09:47:31.388746] <information> mirserver: . |_ Current mode 1600x1600 60.00Hz
[2022-12-07 09:47:31.388768] <information> mirserver: . |_ Preferred mode 1600x1600 60.00Hz
[2022-12-07 09:47:31.388780] <information> mirserver: . |_ Orientation normal
[2022-12-07 09:47:31.388792] <information> mirserver: . |_ Logical size 1600x1600
[2022-12-07 09:47:31.388803] <information> mirserver: . |_ Logical position +0+0
[2022-12-07 09:47:31.388815] <information> mirserver: . |_ Scaling factor: 1.00
./tests/test_bad_buffer.cpp:101: Failure
Failed
Expected protocol error not raised
[2022-12-07 09:47:31.394930] <information> mirserver: Stopping
[  FAILED  ] BadBufferTest.test_truncated_shm_file (19 ms)
```

2022-12-07 10:07 UTC, AlanGriffiths commented on cmake/MirCommon.cmake
> +  if(MIR_BAD_BUFFER_TEST_ENVIRONMENT_BROKEN)
Maybe `MIR_BAD_BUFFER_TEST_ENVIRONMENT_BROKEN` isn't the best name anymore?

2022-12-07 12:42 UTC, Saviq commented
@RAOF I rebased on main and (_I think_) solved the wlcs woes.

2022-12-08 07:10 UTC, RAOF commented
To make review easier I've pulled this apart into the core SHM handling in #2744 and the follow-on implementation of `mf::WlShm`. I think I've resolved the review comments so far that apply to #2744.

2022-12-08 10:07 UTC, closed without merging