Fix race
MirServer/mir pull request #2749
Opened 2022-12-12 15:19 UTC by AlanGriffiths

mf::XWaylandSurface::close() assumes (implicitly) that surface_observer is not set before weak_scene_surface. Make that so.

Fixes: #2733

2022-12-12 22:39 UTC, wmww requested changes
The reason we fatal error if we detect the observer is still alive is because as long as the observer is alive and attached to a `ms::Surface` it may receive observations and call into it's `XWaylandSurface`. This could cause unexpected behavior or a segfault if it happens after `close()` completes.

Previously we created the observer, set `XWaylandSurface::surface_observer` and then created a surface that used that observer. With the new changes we don't set `XWaylandSurface::surface_observer` until after we've created a surface that uses the observer, meaning that it opens us up to getting events after `close()`.

I will look into alternative ways of fixing this, and possibly documenting it better.

2022-12-14 17:30 UTC, wmww approved these changes
LGTM
bors r+

2022-12-15 08:27 UTC, AlanGriffiths commented
bors retry

2022-12-16 10:56 UTC, Saviq commented
bors retry

2022-12-16 16:54 UTC, merged