Fix for mir_performance_tests failure due to not cleaning up our displays
MirServer/mir pull request #3080
Opened 2023-10-13 16:04 UTC by mattkae

## How to test
- On an nvidia + intel platform, run:
```sh
sudo MIR_EXPERIMENTAL_HYBRID_GRAPHICS=1 MIR_SERVER_PLATFORM_RENDERING_LIBS=mir:eglstream-kms XDG_RUNTIME_DIR=/run/ ./bin/mir_performance_tests --gtest_filter=GLMark2Wayland.*
```

2023-10-13 16:44 UTC, AlanGriffiths requested changes
For clarity, should we be testing against `EGL_NO_STREAM_KHR` (for example)?

And this looks like the same issue exists on main and maybe better applied there?

2023-10-16 10:12 UTC, RAOF commented
> For clarity, should we be testing against `EGL_NO_STREAM_KHR` (for example)?

Yeah. I can't find it offhand, but I'm *pretty* sure that there's at least one `EGL_NO_FOO` that's *not* 0.

2023-10-16 13:19 UTC, mattkae commented
> For clarity, should we be testing against `EGL_NO_STREAM_KHR` (for example)?
> 
> And this looks like the same issue exists on main and maybe better applied there?

We are already checking against `EGL_NO_STREAM_KHR` at construction. Unless I am misunderstanding you?

The original error occurs in `DisplayBuffer::post()` at

```
if (nv_stream(dpy).eglStreamConsumerAcquireAttribNV(dpy, output_stream, acquire_attribs) != EGL_TRUE)
...
```

2023-10-16 13:19 UTC, mattkae commented
@AlanGriffiths @RAOF I can move this to `main` if you both think it makes sense. Unless the api-merge is going to main soon, in which case I will hold off

2023-10-17 08:30 UTC, AlanGriffiths requested changes
This is what I meant.

Although, the tests are redundant: they test an invariant established in the constructor. (Which would be more obvious if the members were `const`.)

2023-10-17 08:30 UTC, AlanGriffiths commented on src/platforms/eglstream-kms/server/display.cpp
> +        if (output_stream)
```suggestion
        if (output_stream != EGL_NO_STREAM_KHR)
```

2023-10-17 08:30 UTC, AlanGriffiths commented on src/platforms/eglstream-kms/server/display.cpp
> +        if (ctx)
```suggestion
        if (ctx != EGL_NO_CONTEXT)
```

2023-10-17 14:11 UTC, AlanGriffiths commented on src/platforms/eglstream-kms/server/platform.cpp
> +}
Did I miss committing this comment?

```suggestion
mge::DisplayPlatform::~DisplayPlatform()
{
    if (display != EGL_NO_DISPLAY)
    {
        eglTerminate(display);
    }
}
```

2023-10-17 17:35 UTC, mattkae commented on src/platforms/eglstream-kms/server/platform.cpp
> +}
Yup :)

2023-10-18 08:55 UTC, AlanGriffiths approved these changes

2023-10-18 08:55 UTC, merged