Always rewriting the configuration
MirServer/mir pull request #3082
Opened 2023-10-16 15:37 UTC by mattkae

2023-10-16 16:02 UTC, AlanGriffiths requested changes
I don't think this works well.

Given: the user has supplied a .display configuration with multiple layouts
When: the user overwrites the .display-layout configuration file with a layout name
Then:  Mir switches to the chosen layout

But with this the  .display configuration is overwritten with the current layout. The other layouts are dropped and cannot be selected

2023-10-16 17:12 UTC, mattkae commented
> I don't think this works well.
> 
> Given: the user has supplied a .display configuration with multiple layouts When: the user overwrites the .display-layout configuration file with a layout name Then: Mir switches to the chosen layout
> 
> But with this the .display configuration is overwritten with the current layout. The other layouts are dropped and cannot be selected

Confirmed, I see. :+1: I will rework

2023-10-17 09:14 UTC, AlanGriffiths commented
It doesn't look related, but we have two platforms failing:

```
[ RUN ] RealKMSOutputTest.drm_set_gamma
/spread/mir/tests/unit-tests/platforms/gbm-kms/kms/test_real_kms_output.cpp:516: Failure
Actual function call count doesn't match EXPECT_CALL(mock_drm, drmModeCrtcSetGamma(drm_fd, crtc_ids[0], gamma.red.size(), const_cast<uint16_t*>(gamma.red.data()), const_cast<uint16_t*>(gamma.green.data()), const_cast<uint16_t*>(gamma.blue.data())))...
Expected: to be called once
Actual: never called - unsatisfied and active

[ FAILED ] RealKMSOutputTest.drm_set_gamma (1 ms)
```

2023-10-17 10:03 UTC, Saviq commented
> It doesn't look related, but we have two platforms failing:

That's because we're not merging `main` in CI here, b/c it targets `platform-API-merge`, which is a ways behind `main`.

2023-10-17 10:31 UTC, AlanGriffiths requested changes
In effect, all that's been done here is to separate out the serialization logic from `ReloadingYamlFileDisplayConfig::apply_to()` and call it directly from `MultiplexingDisplay::MultiplexingDisplay()`. That is clearer, and more correct now we have multiple platforms.

But I suspect that adding a `write()` method to `DisplayConfigurationPolicy` would be simpler and less fragile.

2023-10-17 10:31 UTC, AlanGriffiths commented on src/server/symbols.map
> +    mir::Server::override_the_display_configuration_author*;
This is the wrong stanza: these functions were **not** introduced in 2.15

2023-10-17 13:40 UTC, mattkae commented on include/platform/mir/graphics/display_configuration_author.h
> +class DisplayConfigurationAuthor
Scribe is nice :)

2023-10-17 16:13 UTC, AlanGriffiths requested changes
I think we can clean up the commit history

2023-10-17 16:13 UTC, AlanGriffiths commented on include/platform/mir/graphics/display_configuration_policy.h
> +    virtual void confirm(DisplayConfiguration& conf) = 0;
I think `conf` should be `const`

2023-10-17 16:13 UTC, AlanGriffiths commented on src/include/server/mir/server.h
We don't actually need to touch this file

2023-10-17 19:03 UTC, AlanGriffiths approved these changes
OK

2023-10-17 19:03 UTC, merged