Platform: Better names and responsibilities for platform types
MirServer/mir pull request #3114
Opened 2023-11-01 11:51 UTC by RAOF

Currently, most of the `DisplayProvider`s have two responsibilities: providing some global, platform-wide, state, and some sort of allocate-a-display-surface function. That is part of the reason why `DisplayProvider` has been difficult to name.

This splits these concerns out into `DisplayProvider`, providing the global state, and `DisplayAllocator` providing the `DisplayBuffer`-specific allocation services.

This split also allows us to hang the `DisplayAllocator` directly off the `DisplayBuffer`, rather than having a shared intermediate `DisplayInterfaceProvider`.

The new `DisplayBuffer::acquire_allocator<>` continues our tradition of hanging object lifetimes off that of the `DisplayBuffer`, simplifying the interface.

2023-11-01 11:57 UTC, RAOF commented
There's some natural follow-up work to this:
* Now that `DisplayAllocator`s are more directly connected to the `DisplayBuffer`, we can eliminate the `pixel_size()` accessor *and* the `size` parameter to `GLRenderingPlatform::surface_for_output`, as the `DisplayAllocator` can know the only correct value to use there
* It's possible we want to rename `DisplayBuffer`, possibly to `DisplayTarget`? `DisplayBuffer` is no longer anything like a buffer.

2023-11-01 12:16 UTC, AlanGriffiths requested changes
On a skim read looks a sensible approach. Flagged one comment I think is confusing.

Will take a deeper look when I have time

2023-11-01 13:33 UTC, Saviq commented
> Flagged one comment I think is confusing.

Nuh uh! Must've been in a packet that was lost.

2023-11-01 14:06 UTC, AlanGriffiths commented on include/platform/mir/graphics/display_buffer.h
> +            "Can only acquire a DisplayProvider; Provider must implement DisplayAllocator");
`DisplayProvider`?

2023-11-02 12:04 UTC, AlanGriffiths approved these changes
Let's talk about the other renames when you wake up

2023-11-02 13:35 UTC, merged