Make server-side decorations scale aware
MirServer/mir pull request #3153
Opened 2023-11-27 17:16 UTC by hbatagelo

Fixes #1369.

The decoration builder now selects the maximum scale factor among all display outputs, passing it to `msd::BasicDecoration` and `msd::Renderer` to create buffers with a resolution that ensures sharp-looking decorations on all outputs.

2023-12-01 11:44 UTC, AlanGriffiths requested changes
This works and looks fine for the case when outputs remain as configured on startup. But the scale can be reconfigured dynamically (e.g. by updating a "static" `.display` configuration).

The `msd::BasicManager` (or setup) likely needs to register a `DisplayConfigurationObserver` to track scale changes.

2023-12-08 15:00 UTC, hbatagelo commented
`msd::BasicManager` now monitors display changes, updating existing decorations when the scale changes by invoking `Decoration::set_scale` for each decoration.

While this solution seems to work well, it differs from my initial attempt. Initially, I tried rebuilding all decorations when the scale changed, but the behavior was not as I expected. When a window surface is undecorated, the new decoration appears detached from the window, as if the decoration surface is no longer a child of the window surface. I'd like to continue investigating this behavior in order to understand what is causing it. In summary, the current implementation is functional, but if I can fix this new issue I can propose an alternative approach that avoids requiring classes derived from `Decoration` to implement a `set_scale` function.

2023-12-11 15:34 UTC, AlanGriffiths requested changes
> I tried rebuilding all decorations when the scale changed, but the behavior was not as I expected

That sounds like a wrong approach: rescaling ought to be less work than tearing down and rebuilding

2023-12-11 15:34 UTC, AlanGriffiths commented on src/server/shell/decoration/basic_decoration.cpp
> +}
Is access to `scale_` threadsafe? AFAICS it isn't atomic, guarded by a mutex, or guaranteed to be accessed on a single thread

2023-12-11 15:34 UTC, AlanGriffiths commented on src/server/shell/decoration/basic_manager.cpp
> +    scale = max_output_scale;
`scale` is being read and mutated without locking the mutex

2023-12-11 15:34 UTC, AlanGriffiths commented on src/server/shell/decoration/basic_manager.cpp
> +        if (it.second)
I don't think this condition can fail: an empty decoration should not be possible

2023-12-11 15:34 UTC, AlanGriffiths commented on src/server/shell/decoration/basic_manager.h
> +};
I see no reason to make `OutputListener` part of the `basic_manager.h` interface. Or even why we need that interface.

`OutputListener` is only used by `msd::DisplayConfigurationListener` which is implemented entirely in `basic_manager.cpp` and that just needs something to call (e.g. `std::function<void(float new_scale)>`)

2023-12-13 14:11 UTC, hbatagelo commented
- `msd::DisplayConfigurationListener` now inherits from `mg::NullDisplayConfigurationObserver`.
- Usage of `BasicManager::scale` is synchronized under a locked mutex.
- `BasicDecoration::set_scale` is also called under the manager's locked mutex. Since the decorations are uniquely owned by the manager, this should be sufficient to guarantee thread safety.
- Unnecessary `nullptr` checks have been removed. Additionally, test cases for the decoration manager fixture have been updated to ensure the mocked decoration builder returns a valid pointer (the reason the checks were added originally).
- `OutputListener` has been eliminated.
- For consistency, `BasicDecoration::scale_` has been renamed to `BasicDecoration::scale`.

I've also changed the initialization of `decoration_builder` in the constructor of `msd::BasicManager`. The rvalue reference parameter is now moved instead of copied to the member variable.

2023-12-14 16:50 UTC, AlanGriffiths commented
@hbatagelo sorry for the delay reviewing - I ran into a problem (#3165) while testing

2023-12-14 19:38 UTC, hbatagelo commented
No problem. Feel free to postpone the review until #3165 is resolved.

2023-12-15 10:28 UTC, AlanGriffiths approved these changes
Thanks! Looks good now

2023-12-15 11:12 UTC, Saviq approved these changes
Nice and crisp!

![obraz](https://github.com/MirServer/mir/assets/231077/1a3d15d1-4f87-4b17-a400-c0e711616104)

2023-12-15 11:35 UTC, merged