Change placement of new floating windows
MirServer/mir pull request #3187
Opened 2024-01-15 12:53 UTC by hbatagelo

Fixes #3175 using a combination of cascading and random positioning.

Rather than replacing the original algorithm, it has been extended. If the new optically centered window shares the same top-left position as an existing window within a margin of tolerance, the new window is cascaded both vertically and horizontally. Following cascading, if any part of the window extends beyond the display area, it is randomly placed within a "feasible placement region" defined as the morphological erosion of the display region by the window region. If this region is empty, the window is resized horizontally and/or vertically to fit the display area and is also moved to the top and/or left of the display area.

2024-01-15 15:06 UTC, hbatagelo commented
Okay, I'm good with a simpler algorithm, checking the center and corners instead of cascading. Should I keep random placement as a fallback, and the resizing when the window is bigger than the display area?

2024-01-15 16:02 UTC, AlanGriffiths commented
If you're only checking positions against visible windows then it is unlikely that all of the five positions are occupied. (Because, for example, one at NW probably occludes ones at centre, SW, SE and NE.) So fallback the centre is probably good enough, and less confusing than "random".

2024-01-16 10:02 UTC, AlanGriffiths requested changes
There are a lot of tests failing

2024-01-16 10:02 UTC, AlanGriffiths commented on src/miral/basic_window_manager.cpp
> +                     window.top_left() != position)
The logic here seems wrong.

1. `!window` cannot happen: a logic error would have been thrown by `info_for`
2. We don't want to exclude restored windows
3. We don't want to exclude normal and freestyle windows

2024-01-16 10:02 UTC, AlanGriffiths commented on src/miral/basic_window_manager.cpp
> +                auto const window{window_at(position)};
```suggestion
                if (auto const window{window_at(position)})
                {
                    ...
```

2024-01-16 10:13 UTC, AlanGriffiths commented
> There are a lot of tests failing

To run the tests locally:

    cmake --build <build directory> --target ptest

2024-01-16 13:59 UTC, AlanGriffiths commented on src/miral/basic_window_manager.cpp
> +                     window.top_left() != position)
Sorry, I misread the condition (which itself suggests it could be clearer).

2024-01-16 15:03 UTC, AlanGriffiths commented
I tried installing and running this:

```plain
snap install mir-test-tools_pr3187 --channel=22/edge/mir-pr3187
WAYLAND_DISPLAY=wayland-99 mir-test-tools_pr3187.demo-server&
WAYLAND_DISPLAY=wayland-99 gnome-chess&
```

But see the error:

```
[2024-01-16 15:02:02.461418] < -warning- > frontend:Wayland: Exception processing Surface::commit() request: Dynamic exception type: std::out_of_range
std::exception::what: map::at

error in client communication (pid 25499)
Gdk-Message: 15:02:02.461: Error 71 (Protocol error) dispatching to Wayland display.
```

2024-01-16 15:17 UTC, AlanGriffiths commented
> I tried installing and running this:

Building locally doesn't show this effect (and the code looks like it shouldn't). Possibly, the snap store has an old version...

2024-01-16 15:38 UTC, AlanGriffiths approved these changes
The offset used is (obviously) arbitrary and may seem big or small depending on the screen dimensions. (Maybe a fraction of the screen width/height would be better?)

I think the conditional is a bit hard to read, but isn't wrong. I've suggested a rework that might be easier to read (but I am probably biased).

Anyway, does what was asked. So I'll approve and see if anyone else has an opinion.

(Feel free to land with or without my suggestion)

2024-01-16 15:38 UTC, AlanGriffiths commented on src/miral/basic_window_manager.cpp
> +                }
```suggestion
                auto const window{window_at(position)};

                static auto const ignored_state_or_type = [](WindowInfo const& info)
                    {
                        switch (info.type())
                        {
                        case mir_window_type_normal:
                        case mir_window_type_decoration:
                        case mir_window_type_freestyle:
                            return info.state() != mir_window_state_restored;

                        default:
                            return true;
                        }
                    };

                if (!window || ignored_state_or_type(info_for(window)) || window.top_left() != position)
                {
                    parameters.top_left().value() = position;
                    break;
                }
```

2024-01-16 17:15 UTC, mattkae commented
I found a bug that is _maybe_ unrelated to this. It looks like during the startup of miral-shell, all of the windows end up in the same position. In the attached video, I am opening up multiple windows in a row. WDYT @AlanGriffiths , is this blocking?


[Screencast from 01-16-2024 12:15:06 PM.webm](https://github.com/MirServer/mir/assets/25062299/28d8fb84-6882-4bf7-be52-c819ccbacf6a)

2024-01-16 17:22 UTC, hbatagelo commented
I think these first windows are placed at the same position because the splash screen is being displayed. Maybe the splash screen is picked by `window_at` instead of the terminal windows. I'll check.

2024-01-16 17:30 UTC, mattkae commented
> I think these first windows are placed at the same position because the splash screen is being displayed. Maybe the splash screen is picked by `window_at` instead of the terminal windows. I'll check.

Oh good call, that might be it. This could be a separate bug for the splash screen though. If so, we can do it separately :)

2024-01-16 17:30 UTC, AlanGriffiths commented
> WDYT @AlanGriffiths , is this blocking?

I to assume `window_at` is returning the splash screen (because it is on top). Which is a special case I wouldn't block on (you might have a different opinion).

2024-01-16 17:35 UTC, AlanGriffiths commented
> Oh good call, that might be it. This could be a separate bug for the splash screen though. If so, we can do it separately :)

Well, if it is a bug, it is in `window_at()` not the splash screen.

2024-01-16 17:42 UTC, mattkae commented
> I to assume `window_at` is returning the splash screen (because it is on top). Which is a special case I wouldn't block on (you might have a different opinion).

I think it's non-blocking too. As you said, probably a bug in `window_at` that we can record and fix later

2024-01-16 18:00 UTC, hbatagelo commented
I tested locally and can confirm that `window_at` (wrongly) selects the splash screen. Since it is a top-level, freestyle, fullscreen window, placement is allowed at the initial position.

2024-01-16 18:01 UTC, AlanGriffiths commented
> Well, if it is a bug, it is in `window_at()` not the splash screen.

I change my opinion: it is the splash window. This _should_ be transparent to input, and that would ensure it isn't returned by `surface_at`.

But this is pre-existing (e.g. you can't drag a window until the splash animation ends), and not very important.

2024-01-16 19:30 UTC, merged